name: .NET Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"
      - name: Restore dependencies
        run: dotnet restore AspireKeyvaultEmulatorTest.sln
      - name: Build
        run: dotnet build AspireKeyvaultEmulatorTest.sln --no-restore
      - name: Test Without KV
        run: |
          dotnet dev-certs https --trust
          sudo update-ca-certificates
          NOKV=true dotnet test AspireKeyvaultEmulatorTest.sln --no-build --verbosity normal
      - name: Test with KV
        run: |
          dotnet dev-certs https --trust
          sudo update-ca-certificates
          dotnet test AspireKeyvaultEmulatorTest.sln --no-build --verbosity normal
